import type { Recipe } from "@/app/page";

export const cocktailRecipes2: Recipe[] = [
  {
    id: "tom-collins",
    name: "Tom Collins",
    category: "cocktails",
    description: "A fizzy gin classic with lemon and soda",
    rating: "4.5",
    reviews: "900",
    difficulty: "Easy",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Soda Water", amount: "2", unit: "oz" },
    ],
    steps: [
      "Add gin, lemon juice, and syrup to glass with ice",
      "Top with soda water and stir gently",
      "Garnish with lemon wheel",
    ],
    tips: "Use plenty of ice for a refreshing fizz.",
  },
  {
    id: "pina-colada",
    name: "Piña Colada",
    category: "cocktails",
    description: "A creamy tropical blend of rum, coconut, and pineapple",
    rating: "4.7",
    reviews: "1.5k",
    difficulty: "Easy",
    prepTime: "5 mins",
    serves: "1 serving",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Coconut Cream", amount: "1", unit: "oz" },
      { name: "Pineapple Juice", amount: "3", unit: "oz" },
      { name: "Crushed Ice", amount: "1", unit: "cup" },
    ],
    steps: [
      "Add all ingredients to a blender",
      "Blend until smooth and creamy",
      "Pour into hurricane glass",
      "Garnish with pineapple wedge and cherry",
    ],
    tips: "For the best texture, use a combination of crushed ice and frozen pineapple chunks.",
  },
  {
    id: "martini",
    name: "Martini",
    category: "cocktails",
    description: "The quintessential sophisticated cocktail with gin and vermouth",
    rating: "4.8",
    reviews: "1.7k",
    difficulty: "Medium",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Gin", amount: "2.5", unit: "oz" },
      { name: "Dry Vermouth", amount: "0.5", unit: "oz" },
      { name: "Olive or Lemon Twist", amount: "1", unit: "piece" },
    ],
    steps: [
      "Fill mixing glass with ice",
      "Add gin and vermouth",
      "Stir well until very cold",
      "Strain into chilled martini glass",
      "Garnish with olive or lemon twist",
    ],
    tips: "For a drier martini, use less vermouth. For a 'dirty' martini, add a splash of olive brine.",
  },
  {
    id: "moscow-mule",
    name: "Moscow Mule",
    category: "cocktails",
    description: "A zesty, ginger-forward cocktail with vodka and lime",
    rating: "4.6",
    reviews: "1.3k",
    difficulty: "Easy",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Ginger Beer", amount: "4", unit: "oz" },
      { name: "Lime Wedge", amount: "1", unit: "piece" },
    ],
    steps: [
      "Fill copper mug with ice",
      "Add vodka and lime juice",
      "Top with ginger beer and stir gently",
      "Garnish with lime wedge",
    ],
    tips: "Always serve in a copper mug for the authentic experience and optimal temperature.",
  },
  {
    id: "espresso-martini",
    name: "Espresso Martini",
    category: "cocktails",
    description: "A rich, coffee-flavored cocktail with vodka and coffee liqueur",
    rating: "4.8",
    reviews: "1.4k",
    difficulty: "Medium",
    prepTime: "5 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Coffee Liqueur", amount: "1", unit: "oz" },
      { name: "Freshly Brewed Espresso", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
      { name: "Coffee Beans", amount: "3", unit: "pieces" },
    ],
    steps: [
      "Add all ingredients to shaker with ice",
      "Shake vigorously for 20 seconds",
      "Strain into chilled martini glass",
      "Garnish with coffee beans",
    ],
    tips: "Use freshly brewed espresso for the best flavor and texture. The vigorous shake creates the signature foam.",
  },
  {
    id: "dark-n-stormy",
    name: "Dark 'n Stormy",
    category: "cocktails",
    description: "A Bermudian classic with dark rum and spicy ginger beer",
    rating: "4.6",
    reviews: "950",
    difficulty: "Easy",
    prepTime: "2 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Dark Rum", amount: "2", unit: "oz" },
      { name: "Ginger Beer", amount: "4", unit: "oz" },
      { name: "Lime Wedge", amount: "1", unit: "piece" },
    ],
    steps: [
      "Fill highball glass with ice",
      "Pour in ginger beer",
      "Float dark rum on top",
      "Squeeze lime wedge and drop in",
    ],
    tips: "For an authentic Dark 'n Stormy, use Gosling's Black Seal rum.",
  },
  {
    id: "bloody-mary",
    name: "Bloody Mary",
    category: "cocktails",
    description: "A savory morning cocktail with vodka and tomato juice",
    rating: "4.5",
    reviews: "1.2k",
    difficulty: "Medium",
    prepTime: "5 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Tomato Juice", amount: "4", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Worcestershire Sauce", amount: "4", unit: "dashes" },
      { name: "Hot Sauce", amount: "2", unit: "dashes" },
      { name: "Horseradish", amount: "1", unit: "tsp" },
      { name: "Celery Salt", amount: "1", unit: "pinch" },
      { name: "Black Pepper", amount: "1", unit: "pinch" },
      { name: "Celery Stalk", amount: "1", unit: "piece" },
    ],
    steps: [
      "Rim glass with celery salt",
      "Fill glass with ice",
      "Add all liquid ingredients and stir",
      "Add horseradish, celery salt, and pepper",
      "Stir well to combine",
      "Garnish with celery stalk and any additional garnishes",
    ],
    tips: "Customize with garnishes like olives, pickled vegetables, bacon, or even shrimp.",
  },
  {
    id: "amaretto-sour",
    name: "Amaretto Sour",
    category: "cocktails",
    description: "A sweet and sour cocktail with almond-flavored liqueur",
    rating: "4.5",
    reviews: "890",
    difficulty: "Easy",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Amaretto", amount: "1.5", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Egg White (optional)", amount: "0.5", unit: "oz" },
      { name: "Maraschino Cherry", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add all ingredients to a shaker without ice",
      "Dry shake for 15 seconds",
      "Add ice and shake again until chilled",
      "Strain into rocks glass over fresh ice",
      "Garnish with cherry and lemon slice",
    ],
    tips: "For a more complex flavor, add a splash of bourbon or whiskey.",
  },
  {
    id: "paloma",
    name: "Paloma",
    category: "cocktails",
    description: "A refreshing Mexican cocktail with tequila and grapefruit",
    rating: "4.7",
    reviews: "980",
    difficulty: "Easy",
    prepTime: "2 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Fresh Grapefruit Juice", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Agave Syrup", amount: "0.5", unit: "oz" },
      { name: "Soda Water", amount: "2", unit: "oz" },
      { name: "Salt", amount: "1", unit: "pinch" },
    ],
    steps: [
      "Rim glass with salt (optional)",
      "Fill glass with ice",
      "Add tequila, grapefruit juice, lime juice, and agave",
      "Top with soda water and stir gently",
      "Garnish with grapefruit wedge",
    ],
    tips: "Use fresh-squeezed grapefruit juice for the best flavor. Pink grapefruit makes a prettier drink.",
  },
  {
    id: "french-75",
    name: "French 75",
    category: "cocktails",
    description: "An elegant champagne cocktail with gin and lemon",
    rating: "4.8",
    reviews: "850",
    difficulty: "Medium",
    prepTime: "4 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Gin", amount: "1", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Champagne", amount: "3", unit: "oz" },
      { name: "Lemon Twist", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add gin, lemon juice, and simple syrup to shaker with ice",
      "Shake until well chilled",
      "Strain into champagne flute",
      "Top with champagne",
      "Garnish with lemon twist",
    ],
    tips: "Use a good quality dry champagne or sparkling wine. The cocktail should be served very cold.",
  },
]; 