import type { Recipe } from "@/app/page";

export const cocktailRecipes3: Recipe[] = [
  {
    id: "aperol-spritz",
    name: "Aperol Spritz",
    category: "cocktails",
    description: "A popular Italian aperitif with Aperol and Prosecco",
    rating: "4.7",
    reviews: "1.1k",
    difficulty: "Easy",
    prepTime: "2 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Aperol", amount: "2", unit: "oz" },
      { name: "Prosecco", amount: "3", unit: "oz" },
      { name: "Soda Water", amount: "1", unit: "oz" },
      { name: "Orange Slice", amount: "1", unit: "piece" },
    ],
    steps: [
      "Fill wine glass with ice",
      "Add Aperol, Prosecco, and soda water",
      "Stir gently to combine",
      "Garnish with orange slice",
    ],
    tips: "Use chilled Prosecco and serve immediately for the best effervescence.",
  },
  {
    id: "long-island-iced-tea",
    name: "Long Island Iced Tea",
    category: "cocktails",
    description: "A potent mix of five spirits with a deceptively smooth taste",
    rating: "4.5",
    reviews: "1.3k",
    difficulty: "Medium",
    prepTime: "4 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Vodka", amount: "0.5", unit: "oz" },
      { name: "White Rum", amount: "0.5", unit: "oz" },
      { name: "Gin", amount: "0.5", unit: "oz" },
      { name: "Tequila", amount: "0.5", unit: "oz" },
      { name: "Triple Sec", amount: "0.5", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Cola", amount: "2", unit: "oz" },
      { name: "Lemon Wedge", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add all spirits, lemon juice, and simple syrup to shaker with ice",
      "Shake until well chilled",
      "Strain into highball glass filled with ice",
      "Top with cola and stir gently",
      "Garnish with lemon wedge",
    ],
    tips: "Pace yourself with this strong cocktail. Use quality spirits for a smoother taste.",
  },
  {
    id: "sazerac",
    name: "Sazerac",
    category: "cocktails",
    description: "A sophisticated New Orleans classic with rye whiskey and absinthe",
    rating: "4.8",
    reviews: "870",
    difficulty: "Medium",
    prepTime: "4 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Rye Whiskey", amount: "2", unit: "oz" },
      { name: "Absinthe", amount: "0.25", unit: "oz" },
      { name: "Sugar Cube", amount: "1", unit: "piece" },
      { name: "Peychaud's Bitters", amount: "4", unit: "dashes" },
      { name: "Lemon Peel", amount: "1", unit: "piece" },
    ],
    steps: [
      "Rinse chilled old-fashioned glass with absinthe, discard excess",
      "In mixing glass, muddle sugar cube with bitters",
      "Add rye whiskey and ice, stir until well-chilled",
      "Strain into prepared glass",
      "Express lemon peel over drink and discard peel",
    ],
    tips: "The absinthe rinse is essential for the authentic Sazerac experience.",
  },
  {
    id: "gimlet",
    name: "Gimlet",
    category: "cocktails",
    description: "A simple, refreshing cocktail with gin and lime",
    rating: "4.6",
    reviews: "820",
    difficulty: "Easy",
    prepTime: "2 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Lime Wheel", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add gin, lime juice, and simple syrup to shaker with ice",
      "Shake until well chilled",
      "Strain into chilled coupe or martini glass",
      "Garnish with lime wheel",
    ],
    tips: "For a vodka gimlet, simply substitute vodka for gin.",
  },
  {
    id: "white-russian",
    name: "White Russian",
    category: "cocktails",
    description: "A creamy, sweet cocktail with vodka and coffee liqueur",
    rating: "4.7",
    reviews: "1.1k",
    difficulty: "Easy",
    prepTime: "2 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Coffee Liqueur", amount: "1", unit: "oz" },
      { name: "Heavy Cream", amount: "1", unit: "oz" },
    ],
    steps: [
      "Fill old-fashioned glass with ice",
      "Add vodka and coffee liqueur, stir",
      "Float cream on top by pouring over back of a spoon",
      "Serve with straw",
    ],
    tips: "For a different texture, stir all ingredients together instead of floating the cream.",
  },
  {
    id: "mint-julep",
    name: "Mint Julep",
    category: "cocktails",
    description: "A refreshing bourbon cocktail with fresh mint, traditional for the Kentucky Derby",
    rating: "4.6",
    reviews: "950",
    difficulty: "Medium",
    prepTime: "5 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Bourbon Whiskey", amount: "2.5", unit: "oz" },
      { name: "Fresh Mint Leaves", amount: "8-10", unit: "leaves" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Mint Sprig", amount: "1", unit: "piece" },
      { name: "Powdered Sugar", amount: "1", unit: "dash" },
    ],
    steps: [
      "In julep cup or rocks glass, muddle mint leaves with simple syrup",
      "Add bourbon and fill glass with crushed ice",
      "Stir until glass is frosted",
      "Top with more crushed ice to form a dome",
      "Garnish with mint sprig and dust with powdered sugar",
    ],
    tips: "Use a silver julep cup for the authentic experience. The cup should frost on the outside.",
  },
  {
    id: "sidecar",
    name: "Sidecar",
    category: "cocktails",
    description: "A sophisticated cognac cocktail with orange liqueur and lemon",
    rating: "4.7",
    reviews: "780",
    difficulty: "Medium",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Cognac", amount: "2", unit: "oz" },
      { name: "Cointreau", amount: "1", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Sugar Rim (optional)", amount: "1", unit: "teaspoon" },
      { name: "Orange Twist", amount: "1", unit: "piece" },
    ],
    steps: [
      "If desired, rim half the coupe glass with sugar",
      "Add cognac, Cointreau, and lemon juice to shaker with ice",
      "Shake until well chilled",
      "Strain into prepared glass",
      "Garnish with orange twist",
    ],
    tips: "Use quality cognac for the best flavor. The sugar rim is traditional but optional.",
  },
  {
    id: "boulevardier",
    name: "Boulevardier",
    category: "cocktails",
    description: "A whiskey-based variation of the Negroni with a rich, smooth flavor",
    rating: "4.8",
    reviews: "740",
    difficulty: "Medium",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Bourbon or Rye Whiskey", amount: "1.5", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Orange Twist", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add whiskey, Campari, and vermouth to mixing glass with ice",
      "Stir until well chilled",
      "Strain into rocks glass over large ice cube",
      "Garnish with orange twist",
    ],
    tips: "Try with both bourbon and rye to see which you prefer. Bourbon makes it sweeter, rye spicier.",
  },
  {
    id: "caipirinha",
    name: "Caipirinha",
    category: "cocktails",
    description: "Brazil's national cocktail with cachaça, lime, and sugar",
    rating: "4.7",
    reviews: "920",
    difficulty: "Easy",
    prepTime: "3 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Cachaça", amount: "2", unit: "oz" },
      { name: "Lime", amount: "1", unit: "whole" },
      { name: "Sugar", amount: "2", unit: "teaspoons" },
    ],
    steps: [
      "Cut lime into wedges",
      "Muddle lime and sugar in old-fashioned glass",
      "Fill glass with ice",
      "Add cachaça and stir well",
    ],
    tips: "Don't substitute white rum for cachaça, as the flavors are quite different.",
  },
  {
    id: "aviation",
    name: "Aviation",
    category: "cocktails",
    description: "A classic gin cocktail with floral notes and a beautiful color",
    rating: "4.7",
    reviews: "760",
    difficulty: "Medium",
    prepTime: "4 mins",
    serves: "1 serving",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Maraschino Liqueur", amount: "0.5", unit: "oz" },
      { name: "Crème de Violette", amount: "0.25", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Maraschino Cherry", amount: "1", unit: "piece" },
    ],
    steps: [
      "Add all ingredients to shaker with ice",
      "Shake until well chilled",
      "Strain into chilled coupe glass",
      "Garnish with maraschino cherry",
    ],
    tips: "The Crème de Violette gives this cocktail its distinctive color. Without it, the drink is called a Blue Moon.",
  },
]; 