export const recipeData = {
  cocktails: [
    {
      name: "Classic Mojito",
      category: "cocktails",
      description: "A refreshing Cuban cocktail with mint and lime",
      rating: "4.8",
      reviews: "2.1k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "White Rum", amount: "2", unit: "parts" },
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "1", unit: "part" },
        { name: "Soda Water", amount: "2", unit: "parts" },
        { name: "Fresh Mint Leaves", amount: "8-10", unit: "leaves" },
      ],
      steps: [
        "Gently muddle mint leaves in the bottom of a glass",
        "Add rum, lime juice, and simple syrup",
        "Fill glass with ice cubes",
        "Top with soda water and stir gently",
        "Garnish with fresh mint sprig",
      ],
      tips: "Don't over-muddle the mint - you want to release oils, not destroy the leaves.",
    },
    {
      name: "Margarita",
      category: "cocktails",
      description: "The perfect balance of tequila, lime, and orange liqueur",
      rating: "4.7",
      reviews: "1.8k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Tequila", amount: "2", unit: "parts" },
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Orange Liqueur", amount: "1", unit: "part" },
        { name: "Salt", amount: "1", unit: "pinch" },
      ],
      steps: [
        "Rim glass with salt",
        "Add all ingredients to shaker with ice",
        "Shake vigorously for 15 seconds",
        "Strain into prepared glass over ice",
        "Garnish with lime wheel",
      ],
      tips: "Use fresh lime juice for the best flavor. Cointreau or Grand Marnier work best for orange liqueur.",
    },
    {
      name: "Old Fashioned",
      category: "cocktails",
      description: "A timeless whiskey cocktail with bitters and sugar",
      rating: "4.6",
      reviews: "1.5k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Bourbon Whiskey", amount: "2", unit: "parts" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Angostura Bitters", amount: "2-3", unit: "dashes" },
        { name: "Orange Peel", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add simple syrup and bitters to glass",
        "Add whiskey and stir with ice",
        "Strain over large ice cube in rocks glass",
        "Express orange peel oils over drink",
        "Garnish with orange peel",
      ],
      tips: "Use a large ice cube to minimize dilution. Express the orange peel by twisting it over the drink.",
    },
    {
      name: "Negroni",
      category: "cocktails",
      description: "A classic Italian aperitif with gin, Campari, and sweet vermouth",
      rating: "4.7",
      reviews: "1.3k",
      difficulty: "Medium",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Gin", amount: "1", unit: "part" },
        { name: "Campari", amount: "1", unit: "part" },
        { name: "Sweet Vermouth", amount: "1", unit: "part" },
        { name: "Orange Peel", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add gin, Campari, and vermouth to mixing glass with ice",
        "Stir until well chilled",
        "Strain into rocks glass over large ice cube",
        "Garnish with orange peel",
      ],
      tips: "Use equal parts for perfect balance. Stir, don't shake.",
    },
    {
      name: "Manhattan",
      category: "cocktails",
      description: "A sophisticated blend of whiskey, sweet vermouth, and bitters",
      rating: "4.8",
      reviews: "1.6k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Rye Whiskey", amount: "2", unit: "parts" },
        { name: "Sweet Vermouth", amount: "1", unit: "part" },
        { name: "Angostura Bitters", amount: "2", unit: "dashes" },
        { name: "Maraschino Cherry", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add whiskey, vermouth, and bitters to mixing glass with ice",
        "Stir until well chilled",
        "Strain into chilled coupe glass",
        "Garnish with cherry",
      ],
      tips: "Use rye for a spicier profile, bourbon for a sweeter one.",
    },
    {
      name: "Daiquiri",
      category: "cocktails",
      description: "A refreshing Cuban classic with rum, lime, and sugar",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "White Rum", amount: "2", unit: "parts" },
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.75", unit: "part" },
      ],
      steps: [
        "Add all ingredients to shaker with ice",
        "Shake vigorously",
        "Strain into chilled coupe glass",
        "Garnish with lime wheel",
      ],
      tips: "Use fresh lime juice for best results.",
    },
    {
      name: "Whiskey Sour",
      category: "cocktails",
      description: "A tart and smooth blend of whiskey, lemon, and sugar",
      rating: "4.7",
      reviews: "1.4k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Bourbon Whiskey", amount: "2", unit: "parts" },
        { name: "Fresh Lemon Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.75", unit: "part" },
        { name: "Egg White (optional)", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Add all ingredients to shaker without ice and shake (dry shake)",
        "Add ice and shake again",
        "Strain into rocks glass over ice",
        "Garnish with cherry and orange slice",
      ],
      tips: "Egg white adds a silky texture but can be omitted.",
    },
    {
      name: "Cosmopolitan",
      category: "cocktails",
      description: "A stylish pink cocktail with vodka, cranberry, and lime",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Vodka", amount: "1.5", unit: "parts" },
        { name: "Cointreau", amount: "1", unit: "part" },
        { name: "Cranberry Juice", amount: "1", unit: "part" },
        { name: "Fresh Lime Juice", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Add all ingredients to shaker with ice",
        "Shake well",
        "Strain into chilled martini glass",
        "Garnish with lime wheel",
      ],
      tips: "Use unsweetened cranberry juice for a balanced flavor.",
    },
    {
      name: "Mai Tai",
      category: "cocktails",
      description: "A tropical favorite with rum, lime, and orange liqueur",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "White Rum", amount: "1.5", unit: "parts" },
        { name: "Dark Rum", amount: "0.5", unit: "part" },
        { name: "Orange Liqueur", amount: "0.5", unit: "part" },
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Orgeat Syrup", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Add all ingredients except dark rum to shaker with ice",
        "Shake and strain into glass over ice",
        "Float dark rum on top",
        "Garnish with mint and lime",
      ],
      tips: "Orgeat syrup is key for the signature almond flavor.",
    },
    {
      name: "Tom Collins",
      category: "cocktails",
      description: "A fizzy gin classic with lemon and soda",
      rating: "4.5",
      reviews: "900",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Gin", amount: "2", unit: "parts" },
        { name: "Fresh Lemon Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Soda Water", amount: "2", unit: "parts" },
      ],
      steps: [
        "Add gin, lemon juice, and syrup to glass with ice",
        "Top with soda water and stir gently",
        "Garnish with lemon wheel",
      ],
      tips: "Use plenty of ice for a refreshing fizz.",
    },
    {
      name: "Pina Colada",
      category: "cocktails",
      description: "A creamy tropical blend of rum, coconut, and pineapple",
      rating: "4.7",
      reviews: "1.5k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "White Rum", amount: "2", unit: "parts" },
        { name: "Coconut Cream", amount: "1", unit: "part" },
        { name: "Pineapple Juice", amount: "2", unit: "parts" },
      ],
      steps: [
        "Add all ingredients to blender with ice",
        "Blend until smooth",
        "Pour into chilled glass",
        "Garnish with pineapple wedge and cherry",
      ],
      tips: "Use fresh pineapple juice for best flavor.",
    },
    {
      name: "Gin Tonic",
      category: "cocktails",
      description: "A crisp and refreshing gin and tonic",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Gin", amount: "2", unit: "parts" },
        { name: "Tonic Water", amount: "4", unit: "parts" },
        { name: "Lime Wedge", amount: "1", unit: "piece" },
      ],
      steps: [
        "Fill glass with ice",
        "Add gin and tonic water",
        "Stir gently",
        "Garnish with lime wedge",
      ],
      tips: "Use a high-quality tonic for best results.",
    },
    {
      name: "Bloody Mary",
      category: "cocktails",
      description: "A savory brunch classic with vodka and tomato juice",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Medium",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Vodka", amount: "2", unit: "parts" },
        { name: "Tomato Juice", amount: "4", unit: "parts" },
        { name: "Lemon Juice", amount: "0.5", unit: "part" },
        { name: "Worcestershire Sauce", amount: "2", unit: "dashes" },
        { name: "Tabasco", amount: "2", unit: "dashes" },
        { name: "Celery Salt", amount: "1", unit: "pinch" },
        { name: "Black Pepper", amount: "1", unit: "pinch" },
        { name: "Celery Stick", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add all ingredients except celery stick to shaker with ice",
        "Shake gently and strain into glass over ice",
        "Garnish with celery stick",
      ],
      tips: "Adjust Tabasco and Worcestershire to taste.",
    },
    {
      name: "Aperol Spritz",
      category: "cocktails",
      description: "A sparkling Italian aperitif with Aperol and prosecco",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Aperol", amount: "2", unit: "parts" },
        { name: "Prosecco", amount: "3", unit: "parts" },
        { name: "Soda Water", amount: "1", unit: "part" },
        { name: "Orange Slice", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add Aperol, prosecco, and soda to glass with ice",
        "Stir gently",
        "Garnish with orange slice",
      ],
      tips: "Use plenty of ice for a refreshing spritz.",
    },
    {
      name: "French 75",
      category: "cocktails",
      description: "A bubbly blend of gin, lemon, and champagne",
      rating: "4.7",
      reviews: "1.3k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Gin", amount: "1", unit: "part" },
        { name: "Fresh Lemon Juice", amount: "0.5", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Champagne", amount: "3", unit: "parts" },
      ],
      steps: [
        "Add gin, lemon juice, and syrup to shaker with ice",
        "Shake and strain into flute",
        "Top with champagne",
        "Garnish with lemon twist",
      ],
      tips: "Serve in a flute for elegance.",
    },
    {
      name: "Caipirinha",
      category: "cocktails",
      description: "A Brazilian favorite with cachaça, lime, and sugar",
      rating: "4.5",
      reviews: "900",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Cachaça", amount: "2", unit: "parts" },
        { name: "Fresh Lime", amount: "1", unit: "whole, cut into wedges" },
        { name: "Sugar", amount: "2", unit: "tsp" },
      ],
      steps: [
        "Muddle lime and sugar in glass",
        "Add cachaça and ice",
        "Stir well",
      ],
      tips: "Use plenty of ice for a refreshing drink.",
    },
    {
      name: "Moscow Mule",
      category: "cocktails",
      description: "A spicy, refreshing mix of vodka, ginger beer, and lime",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Vodka", amount: "2", unit: "parts" },
        { name: "Ginger Beer", amount: "4", unit: "parts" },
        { name: "Fresh Lime Juice", amount: "0.5", unit: "part" },
        { name: "Lime Wedge", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add vodka and lime juice to mug with ice",
        "Top with ginger beer",
        "Stir gently",
        "Garnish with lime wedge",
      ],
      tips: "Serve in a copper mug for tradition and chill.",
    },
    {
      name: "Sidecar",
      category: "cocktails",
      description: "A citrusy, brandy-based classic",
      rating: "4.5",
      reviews: "950",
      difficulty: "Medium",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Cognac", amount: "2", unit: "parts" },
        { name: "Cointreau", amount: "1", unit: "part" },
        { name: "Fresh Lemon Juice", amount: "1", unit: "part" },
      ],
      steps: [
        "Add all ingredients to shaker with ice",
        "Shake and strain into coupe glass",
        "Garnish with lemon twist",
      ],
      tips: "Chill the glass for best results.",
    },
    {
      name: "Sazerac",
      category: "cocktails",
      description: "A New Orleans classic with rye, bitters, and absinthe rinse",
      rating: "4.7",
      reviews: "1.0k",
      difficulty: "Hard",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Rye Whiskey", amount: "2", unit: "parts" },
        { name: "Sugar Cube", amount: "1", unit: "piece" },
        { name: "Peychaud's Bitters", amount: "3", unit: "dashes" },
        { name: "Absinthe", amount: "1", unit: "rinse" },
        { name: "Lemon Peel", amount: "1", unit: "piece" },
      ],
      steps: [
        "Rinse glass with absinthe and discard excess",
        "Muddle sugar and bitters, add rye and ice, stir",
        "Strain into prepared glass",
        "Garnish with lemon peel",
      ],
      tips: "Use a chilled, heavy-bottomed glass for tradition.",
    },
    {
      name: "Mint Julep",
      category: "cocktails",
      description: "A Southern favorite with bourbon, mint, and sugar",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Bourbon Whiskey", amount: "2", unit: "parts" },
        { name: "Fresh Mint Leaves", amount: "8-10", unit: "leaves" },
        { name: "Sugar", amount: "0.5", unit: "part" },
        { name: "Crushed Ice", amount: "1", unit: "cup" },
      ],
      steps: [
        "Muddle mint and sugar in glass",
        "Add bourbon and crushed ice",
        "Stir until glass frosts",
        "Garnish with mint sprig",
      ],
      tips: "Serve in a silver or pewter cup for tradition.",
    },
    {
      name: "Boulevardier",
      category: "cocktails",
      description: "A whiskey-based cousin of the Negroni",
      rating: "4.5",
      reviews: "900",
      difficulty: "Medium",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Bourbon or Rye Whiskey", amount: "1.5", unit: "parts" },
        { name: "Campari", amount: "1", unit: "part" },
        { name: "Sweet Vermouth", amount: "1", unit: "part" },
        { name: "Orange Peel", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add all ingredients to mixing glass with ice",
        "Stir until well chilled",
        "Strain into rocks glass over ice",
        "Garnish with orange peel",
      ],
      tips: "Try with rye for a spicier twist.",
    },
    {
      name: "Rum Punch",
      category: "cocktails",
      description: "A fruity, crowd-pleasing rum cocktail",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Dark Rum", amount: "2", unit: "parts" },
        { name: "Pineapple Juice", amount: "2", unit: "parts" },
        { name: "Orange Juice", amount: "1", unit: "part" },
        { name: "Grenadine", amount: "0.5", unit: "part" },
        { name: "Lime Juice", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Add all ingredients to shaker with ice",
        "Shake and strain into glass over ice",
        "Garnish with orange slice and cherry",
      ],
      tips: "Adjust juice ratios to taste for your crowd.",
    },
  ],
  coffee: [
    {
      name: "Espresso Martini",
      category: "coffee",
      description: "The perfect marriage of coffee and cocktail",
      rating: "4.9",
      reviews: "3.2k",
      difficulty: "Medium",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Vodka", amount: "2", unit: "parts" },
        { name: "Fresh Espresso", amount: "1", unit: "part" },
        { name: "Coffee Liqueur", amount: "0.5", unit: "part" },
        { name: "Simple Syrup", amount: "0.25", unit: "part" },
      ],
      steps: [
        "Brew fresh espresso and let cool slightly",
        "Add all ingredients to shaker with ice",
        "Shake vigorously for 15 seconds",
        "Double strain into chilled coupe glass",
        "Garnish with three coffee beans",
      ],
      tips: "The espresso should be fresh but not hot. The foam on top comes from proper shaking technique.",
    },
    {
      name: "Café Latte",
      category: "coffee",
      description: "Smooth espresso with steamed milk and light foam",
      rating: "4.7",
      reviews: "2.8k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Steamed Milk", amount: "3", unit: "parts" },
        { name: "Milk Foam", amount: "1", unit: "part" },
      ],
      steps: [
        "Extract fresh espresso into cup",
        "Steam milk to 150-160°F",
        "Pour steamed milk into espresso",
        "Top with light layer of foam",
        "Optional: create latte art",
      ],
      tips: "Steam milk to the right temperature - too hot will scald and taste bitter.",
    },
    {
      name: "Americano",
      category: "coffee",
      description: "Espresso diluted with hot water for a smooth, long coffee.",
      rating: "4.6",
      reviews: "2.1k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Hot Water", amount: "2", unit: "parts" },
      ],
      steps: [
        "Extract espresso into cup",
        "Add hot water to espresso",
        "Stir gently and serve",
      ],
      tips: "Adjust water ratio for strength preference.",
    },
    {
      name: "Cappuccino",
      category: "coffee",
      description: "Espresso with steamed milk and a thick layer of foam.",
      rating: "4.8",
      reviews: "3.0k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Steamed Milk", amount: "1", unit: "part" },
        { name: "Milk Foam", amount: "1", unit: "part" },
      ],
      steps: [
        "Extract espresso into cup",
        "Add steamed milk",
        "Top with thick layer of foam",
      ],
      tips: "Use equal parts espresso, steamed milk, and foam.",
    },
    {
      name: "Flat White",
      category: "coffee",
      description: "A velvety blend of espresso and microfoam, popular in Australia and New Zealand.",
      rating: "4.7",
      reviews: "2.2k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Steamed Milk (microfoam)", amount: "2", unit: "parts" },
      ],
      steps: [
        "Extract espresso into cup",
        "Add steamed milk with microfoam",
        "Serve immediately",
      ],
      tips: "Use whole milk for best microfoam texture.",
    },
    {
      name: "Macchiato",
      category: "coffee",
      description: "Espresso marked with a small amount of milk foam.",
      rating: "4.5",
      reviews: "1.5k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Milk Foam", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Extract espresso into small cup",
        "Top with a spoonful of milk foam",
      ],
      tips: "Great for those who like strong coffee with a touch of creaminess.",
    },
    {
      name: "Mocha",
      category: "coffee",
      description: "A chocolate-flavored coffee drink with espresso, steamed milk, and cocoa.",
      rating: "4.8",
      reviews: "2.7k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Steamed Milk", amount: "2", unit: "parts" },
        { name: "Chocolate Syrup", amount: "1", unit: "part" },
        { name: "Whipped Cream", amount: "1", unit: "dollop" },
      ],
      steps: [
        "Mix chocolate syrup with espresso",
        "Add steamed milk",
        "Top with whipped cream",
      ],
      tips: "Dust with cocoa powder for extra flavor.",
    },
    {
      name: "Affogato",
      category: "coffee",
      description: "A scoop of vanilla ice cream drowned with hot espresso.",
      rating: "4.9",
      reviews: "1.9k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Vanilla Ice Cream", amount: "1", unit: "scoop" },
        { name: "Espresso", amount: "1", unit: "shot" },
      ],
      steps: [
        "Place ice cream in a small bowl or glass",
        "Pour hot espresso over ice cream",
        "Serve immediately",
      ],
      tips: "Try with hazelnut or chocolate ice cream for a twist.",
    },
    {
      name: "Irish Coffee",
      category: "coffee",
      description: "Hot coffee with Irish whiskey, sugar, and a layer of cream.",
      rating: "4.7",
      reviews: "1.8k",
      difficulty: "Medium",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Hot Coffee", amount: "1", unit: "cup" },
        { name: "Irish Whiskey", amount: "1.5", unit: "oz" },
        { name: "Brown Sugar", amount: "1", unit: "tsp" },
        { name: "Heavy Cream", amount: "1", unit: "oz" },
      ],
      steps: [
        "Dissolve sugar in hot coffee",
        "Add whiskey and stir",
        "Float cream on top by pouring over the back of a spoon",
      ],
      tips: "Do not stir after adding cream; drink through the cream.",
    },
    {
      name: "Cortado",
      category: "coffee",
      description: "Equal parts espresso and steamed milk, Spanish style.",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Steamed Milk", amount: "1", unit: "part" },
      ],
      steps: [
        "Extract espresso into small glass",
        "Add steamed milk",
      ],
      tips: "Great for those who want less milk than a latte.",
    },
    {
      name: "Ristretto",
      category: "coffee",
      description: "A short shot of espresso, more concentrated and less bitter.",
      rating: "4.5",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Finely Ground Coffee", amount: "1", unit: "part" },
        { name: "Water", amount: "0.75", unit: "part" },
      ],
      steps: [
        "Extract a short shot of espresso",
        "Serve immediately",
      ],
      tips: "Use less water for a more intense flavor.",
    },
    {
      name: "Doppio",
      category: "coffee",
      description: "A double shot of espresso for a stronger coffee experience.",
      rating: "4.7",
      reviews: "1.6k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "2", unit: "shots" },
      ],
      steps: [
        "Extract two shots of espresso into cup",
        "Serve immediately",
      ],
      tips: "Use freshly ground beans for best crema.",
    },
    {
      name: "Vienna Coffee",
      category: "coffee",
      description: "Espresso topped with whipped cream, a European classic.",
      rating: "4.6",
      reviews: "1.3k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Whipped Cream", amount: "1", unit: "dollop" },
      ],
      steps: [
        "Extract espresso into cup",
        "Top with whipped cream",
      ],
      tips: "Dust with cocoa or cinnamon for extra flavor.",
    },
    {
      name: "Iced Coffee",
      category: "coffee",
      description: "Chilled brewed coffee served over ice, refreshing and simple.",
      rating: "4.5",
      reviews: "2.0k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Brewed Coffee", amount: "1", unit: "cup" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew coffee and let cool",
        "Pour over ice cubes in glass",
        "Serve immediately",
      ],
      tips: "Use strong coffee to avoid dilution.",
    },
    {
      name: "Cold Brew",
      category: "coffee",
      description: "Coffee brewed slowly with cold water for a smooth, less acidic taste.",
      rating: "4.8",
      reviews: "2.5k",
      difficulty: "Medium",
      prepTime: "12 hrs",
      serves: "2 servings",
      ingredients: [
        { name: "Coarse Ground Coffee", amount: "1", unit: "cup" },
        { name: "Cold Water", amount: "4", unit: "cups" },
      ],
      steps: [
        "Combine coffee and water in jar",
        "Steep in fridge for 12 hours",
        "Strain and serve over ice",
      ],
      tips: "Dilute with water or milk to taste.",
    },
    {
      name: "Turkish Coffee",
      category: "coffee",
      description: "Finely ground coffee simmered with sugar and cardamom, unfiltered.",
      rating: "4.7",
      reviews: "1.4k",
      difficulty: "Medium",
      prepTime: "7 mins",
      serves: "2 servings",
      ingredients: [
        { name: "Finely Ground Coffee", amount: "2", unit: "tsp" },
        { name: "Sugar", amount: "1", unit: "tsp" },
        { name: "Cardamom (optional)", amount: "1", unit: "pinch" },
        { name: "Water", amount: "1", unit: "cup" },
      ],
      steps: [
        "Combine all ingredients in cezve (small pot)",
        "Heat slowly until foam rises",
        "Pour into small cups, grounds and all",
      ],
      tips: "Let grounds settle before sipping.",
    },
    {
      name: "Espresso Con Panna",
      category: "coffee",
      description: "Espresso topped with a dollop of whipped cream.",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Whipped Cream", amount: "1", unit: "dollop" },
      ],
      steps: [
        "Extract espresso into cup",
        "Top with whipped cream",
      ],
      tips: "Serve in a demitasse cup for tradition.",
    },
    {
      name: "Red Eye",
      category: "coffee",
      description: "Brewed coffee with a shot of espresso for extra kick.",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Brewed Coffee", amount: "1", unit: "cup" },
        { name: "Espresso", amount: "1", unit: "shot" },
      ],
      steps: [
        "Brew coffee",
        "Add shot of espresso to coffee",
        "Serve immediately",
      ],
      tips: "Great for late nights or early mornings.",
    },
    {
      name: "Piccolo Latte",
      category: "coffee",
      description: "A mini latte made with a single ristretto shot and steamed milk.",
      rating: "4.4",
      reviews: "900",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Ristretto", amount: "1", unit: "shot" },
        { name: "Steamed Milk", amount: "1", unit: "part" },
      ],
      steps: [
        "Extract ristretto into small glass",
        "Add steamed milk",
      ],
      tips: "Serve in a small glass for authenticity.",
    },
    {
      name: "Espresso Romano",
      category: "coffee",
      description: "Espresso served with a slice of lemon for a citrusy twist.",
      rating: "4.3",
      reviews: "800",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Espresso", amount: "1", unit: "part" },
        { name: "Lemon Slice", amount: "1", unit: "piece" },
      ],
      steps: [
        "Extract espresso into cup",
        "Serve with lemon slice on the side",
      ],
      tips: "Rub lemon on cup rim for extra aroma.",
    },
  ],
  tea: [
    {
      name: "Earl Grey Martini",
      category: "tea",
      description: "An elegant twist on the classic martini with bergamot",
      rating: "4.6",
      reviews: "892",
      difficulty: "Medium",
      prepTime: "6 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Gin", amount: "2", unit: "parts" },
        { name: "Earl Grey Tea (cooled)", amount: "1", unit: "part" },
        { name: "Dry Vermouth", amount: "0.5", unit: "part" },
        { name: "Lemon Twist", amount: "1", unit: "piece" },
      ],
      steps: [
        "Brew strong Earl Grey tea and cool completely",
        "Add gin, tea, and vermouth to mixing glass with ice",
        "Stir for 30 seconds",
        "Strain into chilled coupe glass",
        "Garnish with lemon twist",
      ],
      tips: "Brew the tea strong and let it cool completely before mixing to avoid dilution.",
    },
    {
      name: "Matcha Latte",
      category: "tea",
      description: "Ceremonial grade matcha with perfectly steamed milk",
      rating: "4.8",
      reviews: "1.4k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Matcha Powder", amount: "1", unit: "tsp" },
        { name: "Hot Water", amount: "2", unit: "tbsp" },
        { name: "Steamed Milk", amount: "6", unit: "oz" },
        { name: "Honey", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Sift matcha powder into bowl",
        "Add hot water and whisk until smooth",
        "Add honey and mix well",
        "Pour into cup and add steamed milk",
        "Create foam art if desired",
      ],
      tips: "Use ceremonial grade matcha for the best flavor and color.",
    },
    {
      name: "London Fog",
      category: "tea",
      description: "Earl Grey tea with steamed milk and vanilla syrup.",
      rating: "4.7",
      reviews: "1.5k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Earl Grey Tea", amount: "1", unit: "bag" },
        { name: "Steamed Milk", amount: "1", unit: "cup" },
        { name: "Vanilla Syrup", amount: "1", unit: "tbsp" },
      ],
      steps: [
        "Brew Earl Grey tea",
        "Add vanilla syrup",
        "Top with steamed milk",
      ],
      tips: "Use strong tea for best flavor.",
    },
    {
      name: "Chai Latte",
      category: "tea",
      description: "Spiced black tea with steamed milk, a warming Indian classic.",
      rating: "4.8",
      reviews: "2.2k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Chai Tea", amount: "1", unit: "bag" },
        { name: "Steamed Milk", amount: "1", unit: "cup" },
        { name: "Honey", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Brew chai tea",
        "Add honey",
        "Top with steamed milk",
      ],
      tips: "Sprinkle with cinnamon for extra warmth.",
    },
    {
      name: "Thai Iced Tea",
      category: "tea",
      description: "Sweet and creamy black tea served over ice, a Thai favorite.",
      rating: "4.7",
      reviews: "1.9k",
      difficulty: "Medium",
      prepTime: "6 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "2", unit: "bags" },
        { name: "Sweetened Condensed Milk", amount: "2", unit: "tbsp" },
        { name: "Sugar", amount: "1", unit: "tbsp" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew strong black tea",
        "Add sugar and condensed milk, stir well",
        "Pour over ice",
      ],
      tips: "Use Ceylon tea for authentic flavor.",
    },
    {
      name: "Bubble Milk Tea",
      category: "tea",
      description: "Taiwanese black tea with milk and chewy tapioca pearls.",
      rating: "4.9",
      reviews: "3.1k",
      difficulty: "Medium",
      prepTime: "8 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "1", unit: "bag" },
        { name: "Milk", amount: "1", unit: "cup" },
        { name: "Tapioca Pearls", amount: "1/4", unit: "cup" },
        { name: "Sugar Syrup", amount: "1", unit: "tbsp" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew black tea and let cool",
        "Cook tapioca pearls as directed",
        "Combine tea, milk, syrup, and pearls in glass",
        "Add ice and serve with wide straw",
      ],
      tips: "Adjust sweetness to taste.",
    },
    {
      name: "Moroccan Mint Tea",
      category: "tea",
      description: "Green tea with fresh mint and sugar, a North African tradition.",
      rating: "4.6",
      reviews: "1.3k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Green Tea", amount: "1", unit: "bag" },
        { name: "Fresh Mint", amount: "6", unit: "leaves" },
        { name: "Sugar", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Brew green tea",
        "Add mint and sugar",
        "Steep for 2 minutes and serve",
      ],
      tips: "Pour from a height for froth.",
    },
    {
      name: "Iced Lemon Tea",
      category: "tea",
      description: "Black tea with lemon and sugar, served over ice.",
      rating: "4.5",
      reviews: "1.7k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "1", unit: "bag" },
        { name: "Lemon Juice", amount: "2", unit: "tbsp" },
        { name: "Sugar", amount: "1", unit: "tbsp" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew black tea and let cool",
        "Add lemon juice and sugar",
        "Pour over ice and serve",
      ],
      tips: "Garnish with lemon slice.",
    },
    {
      name: "Peach Green Tea",
      category: "tea",
      description: "Green tea with peach syrup, a fruity and refreshing drink.",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Green Tea", amount: "1", unit: "bag" },
        { name: "Peach Syrup", amount: "2", unit: "tbsp" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew green tea and let cool",
        "Add peach syrup",
        "Pour over ice and serve",
      ],
      tips: "Use fresh peach puree for natural flavor.",
    },
    {
      name: "Thai Milk Tea",
      category: "tea",
      description: "Sweet black tea with milk, a creamy Thai favorite.",
      rating: "4.7",
      reviews: "1.8k",
      difficulty: "Medium",
      prepTime: "6 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "2", unit: "bags" },
        { name: "Sweetened Condensed Milk", amount: "2", unit: "tbsp" },
        { name: "Evaporated Milk", amount: "2", unit: "tbsp" },
        { name: "Sugar", amount: "1", unit: "tbsp" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew strong black tea",
        "Add sugar, condensed milk, and evaporated milk",
        "Stir well and pour over ice",
      ],
      tips: "Use a tall glass for best presentation.",
    },
    {
      name: "Jasmine Milk Tea",
      category: "tea",
      description: "Fragrant jasmine tea with milk and a touch of sweetness.",
      rating: "4.6",
      reviews: "1.4k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Jasmine Tea", amount: "1", unit: "bag" },
        { name: "Milk", amount: "1", unit: "cup" },
        { name: "Sugar Syrup", amount: "1", unit: "tbsp" },
      ],
      steps: [
        "Brew jasmine tea and let cool",
        "Add milk and syrup",
        "Serve over ice",
      ],
      tips: "Use whole milk for creaminess.",
    },
    {
      name: "Arnold Palmer",
      category: "tea",
      description: "A refreshing mix of iced tea and lemonade, named after the golfer.",
      rating: "4.5",
      reviews: "1.6k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "1", unit: "bag" },
        { name: "Lemonade", amount: "1", unit: "cup" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Brew black tea and let cool",
        "Mix with lemonade",
        "Serve over ice",
      ],
      tips: "Adjust tea-to-lemonade ratio to taste.",
    },
    {
      name: "Hong Kong Milk Tea",
      category: "tea",
      description: "Strong black tea with evaporated or condensed milk, a Hong Kong staple.",
      rating: "4.7",
      reviews: "2.0k",
      difficulty: "Medium",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "2", unit: "bags" },
        { name: "Evaporated Milk", amount: "2", unit: "tbsp" },
        { name: "Sugar", amount: "1", unit: "tbsp" },
      ],
      steps: [
        "Brew strong black tea",
        "Add evaporated milk and sugar",
        "Stir and serve",
      ],
      tips: "Strain tea through a fine mesh for smoothness.",
    },
    {
      name: "Fruit Tea Punch",
      category: "tea",
      description: "A party punch with black tea, fruit juice, and fresh fruit.",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "2 servings",
      ingredients: [
        { name: "Black Tea", amount: "2", unit: "bags" },
        { name: "Orange Juice", amount: "1/2", unit: "cup" },
        { name: "Pineapple Juice", amount: "1/2", unit: "cup" },
        { name: "Lemon Juice", amount: "2", unit: "tbsp" },
        { name: "Fresh Fruit", amount: "1/2", unit: "cup" },
      ],
      steps: [
        "Brew black tea and let cool",
        "Mix with juices and fruit",
        "Serve over ice",
      ],
      tips: "Add sparkling water for fizz.",
    },
    {
      name: "Ginger Lemon Tea",
      category: "tea",
      description: "Soothing black tea with ginger and lemon, great for colds.",
      rating: "4.7",
      reviews: "1.3k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "1", unit: "bag" },
        { name: "Fresh Ginger", amount: "3", unit: "slices" },
        { name: "Lemon Juice", amount: "1", unit: "tbsp" },
        { name: "Honey", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Brew black tea with ginger",
        "Add lemon juice and honey",
        "Serve hot",
      ],
      tips: "Add more ginger for extra spice.",
    },
    {
      name: "Rose Milk Tea",
      category: "tea",
      description: "Fragrant rose tea with milk and a hint of sweetness.",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Rose Tea", amount: "1", unit: "bag" },
        { name: "Milk", amount: "1", unit: "cup" },
        { name: "Sugar Syrup", amount: "1", unit: "tbsp" },
      ],
      steps: [
        "Brew rose tea and let cool",
        "Add milk and syrup",
        "Serve over ice",
      ],
      tips: "Garnish with dried rose petals.",
    },
    {
      name: "Apple Cinnamon Tea",
      category: "tea",
      description: "Black tea with apple juice and cinnamon, a cozy autumn drink.",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Black Tea", amount: "1", unit: "bag" },
        { name: "Apple Juice", amount: "1/2", unit: "cup" },
        { name: "Cinnamon Stick", amount: "1", unit: "piece" },
        { name: "Honey", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Brew black tea",
        "Add apple juice, cinnamon, and honey",
        "Serve hot",
      ],
      tips: "Garnish with apple slices.",
    },
    {
      name: "Osmanthus Oolong Tea",
      category: "tea",
      description: "Floral oolong tea with osmanthus flowers, a Chinese favorite.",
      rating: "4.7",
      reviews: "1.1k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Oolong Tea", amount: "1", unit: "bag" },
        { name: "Osmanthus Flowers", amount: "1", unit: "tsp" },
        { name: "Honey", amount: "1", unit: "tsp" },
      ],
      steps: [
        "Brew oolong tea with osmanthus flowers",
        "Add honey and stir",
        "Serve hot or cold",
      ],
      tips: "Use fresh osmanthus for best aroma.",
    },
  ],
  mocktails: [
    {
      name: "Virgin Mojito",
      category: "mocktails",
      description: "All the refreshing taste of mojito without the alcohol",
      rating: "4.5",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "1", unit: "part" },
        { name: "Soda Water", amount: "3", unit: "parts" },
        { name: "Fresh Mint Leaves", amount: "8-10", unit: "leaves" },
      ],
      steps: [
        "Gently muddle mint leaves in glass",
        "Add lime juice and simple syrup",
        "Fill with ice cubes",
        "Top with soda water",
        "Garnish with mint sprig and lime wheel",
      ],
      tips: "Use plenty of fresh mint for the best flavor impact.",
    },
    {
      name: "Cucumber Cooler",
      category: "mocktails",
      description: "A refreshing blend of cucumber and herbs",
      rating: "4.4",
      reviews: "756",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Cucumber", amount: "4", unit: "slices" },
        { name: "Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Soda Water", amount: "3", unit: "parts" },
        { name: "Fresh Basil", amount: "3-4", unit: "leaves" },
      ],
      steps: [
        "Muddle cucumber and basil in shaker",
        "Add lime juice and simple syrup",
        "Shake with ice",
        "Strain into glass over ice",
        "Top with soda water and garnish",
      ],
      tips: "Muddle gently to avoid bitter flavors from over-bruised herbs.",
    },
    {
      name: "Virgin Pina Colada",
      category: "mocktails",
      description: "A tropical blend of pineapple juice, coconut cream, and ice, without the rum.",
      rating: "4.7",
      reviews: "1.8k",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Pineapple Juice", amount: "2", unit: "parts" },
        { name: "Coconut Cream", amount: "1", unit: "part" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Blend pineapple juice, coconut cream, and ice until smooth",
        "Pour into glass",
        "Garnish with pineapple wedge and cherry",
      ],
      tips: "Use fresh pineapple juice for best flavor.",
    },
    {
      name: "Virgin Sangria",
      category: "mocktails",
      description: "A fruity punch with grape juice, fresh fruit, and sparkling water.",
      rating: "4.6",
      reviews: "1.5k",
      difficulty: "Easy",
      prepTime: "5 mins",
      serves: "2 servings",
      ingredients: [
        { name: "Grape Juice", amount: "2", unit: "cups" },
        { name: "Orange Juice", amount: "1", unit: "cup" },
        { name: "Fresh Fruit", amount: "1", unit: "cup" },
        { name: "Sparkling Water", amount: "1", unit: "cup" },
      ],
      steps: [
        "Mix grape juice and orange juice",
        "Add fresh fruit",
        "Top with sparkling water",
        "Serve over ice",
      ],
      tips: "Let fruit soak for 30 minutes for best flavor.",
    },
    {
      name: "Virgin Mojito",
      category: "mocktails",
      description: "A refreshing mix of lime, mint, and soda water, without the rum.",
      rating: "4.5",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "1", unit: "part" },
        { name: "Soda Water", amount: "3", unit: "parts" },
        { name: "Fresh Mint Leaves", amount: "8-10", unit: "leaves" },
      ],
      steps: [
        "Gently muddle mint leaves in glass",
        "Add lime juice and simple syrup",
        "Fill with ice cubes",
        "Top with soda water",
        "Garnish with mint sprig and lime wheel",
      ],
      tips: "Use plenty of fresh mint for the best flavor impact.",
    },
    {
      name: "Virgin Margarita",
      category: "mocktails",
      description: "A tangy blend of lime, orange, and agave, without the tequila.",
      rating: "4.4",
      reviews: "1.0k",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Orange Juice", amount: "1", unit: "part" },
        { name: "Agave Syrup", amount: "0.5", unit: "part" },
        { name: "Salt", amount: "1", unit: "pinch" },
      ],
      steps: [
        "Rim glass with salt",
        "Mix lime juice, orange juice, and agave syrup",
        "Pour over ice",
        "Garnish with lime wheel",
      ],
      tips: "Adjust sweetness to taste.",
    },
    {
      name: "Virgin Bloody Mary",
      category: "mocktails",
      description: "A savory mix of tomato juice, spices, and lemon, without the vodka.",
      rating: "4.3",
      reviews: "900",
      difficulty: "Medium",
      prepTime: "5 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Tomato Juice", amount: "4", unit: "parts" },
        { name: "Lemon Juice", amount: "0.5", unit: "part" },
        { name: "Worcestershire Sauce", amount: "2", unit: "dashes" },
        { name: "Tabasco", amount: "2", unit: "dashes" },
        { name: "Celery Salt", amount: "1", unit: "pinch" },
        { name: "Black Pepper", amount: "1", unit: "pinch" },
        { name: "Celery Stick", amount: "1", unit: "piece" },
      ],
      steps: [
        "Mix tomato juice, lemon juice, and spices",
        "Pour over ice",
        "Garnish with celery stick",
      ],
      tips: "Adjust Tabasco and Worcestershire to taste.",
    },
    {
      name: "Virgin Daiquiri",
      category: "mocktails",
      description: "A sweet and tart blend of lime and sugar, without the rum.",
      rating: "4.2",
      reviews: "800",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.75", unit: "part" },
        { name: "Ice Cubes", amount: "1", unit: "cup" },
      ],
      steps: [
        "Blend lime juice, simple syrup, and ice until smooth",
        "Pour into glass",
        "Garnish with lime wheel",
      ],
      tips: "Use fresh lime juice for best results.",
    },
    {
      name: "Virgin Cosmopolitan",
      category: "mocktails",
      description: "A pink blend of cranberry, lime, and orange, without the vodka.",
      rating: "4.1",
      reviews: "700",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Cranberry Juice", amount: "1", unit: "part" },
        { name: "Orange Juice", amount: "1", unit: "part" },
        { name: "Fresh Lime Juice", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Mix cranberry juice, orange juice, and lime juice",
        "Pour over ice",
        "Garnish with lime wheel",
      ],
      tips: "Use unsweetened cranberry juice for a balanced flavor.",
    },
    {
      name: "Virgin Mai Tai",
      category: "mocktails",
      description: "A tropical blend of pineapple, orange, and lime, without the rum.",
      rating: "4.0",
      reviews: "600",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Pineapple Juice", amount: "1.5", unit: "parts" },
        { name: "Orange Juice", amount: "0.5", unit: "part" },
        { name: "Fresh Lime Juice", amount: "1", unit: "part" },
        { name: "Orgeat Syrup", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Mix pineapple juice, orange juice, lime juice, and orgeat syrup",
        "Pour over ice",
        "Garnish with mint and lime",
      ],
      tips: "Orgeat syrup is key for the signature almond flavor.",
    },
    {
      name: "Virgin Tom Collins",
      category: "mocktails",
      description: "A fizzy blend of lemon, sugar, and soda water, without the gin.",
      rating: "3.9",
      reviews: "500",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lemon Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Soda Water", amount: "2", unit: "parts" },
      ],
      steps: [
        "Mix lemon juice and simple syrup",
        "Top with soda water",
        "Garnish with lemon wheel",
      ],
      tips: "Use plenty of ice for a refreshing fizz.",
    },
    {
      name: "Virgin Gin Tonic",
      category: "mocktails",
      description: "A crisp blend of tonic water and lime, without the gin.",
      rating: "3.8",
      reviews: "400",
      difficulty: "Easy",
      prepTime: "2 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Tonic Water", amount: "4", unit: "parts" },
        { name: "Lime Wedge", amount: "1", unit: "piece" },
      ],
      steps: [
        "Fill glass with ice",
        "Add tonic water",
        "Garnish with lime wedge",
      ],
      tips: "Use a high-quality tonic for best results.",
    },
    {
      name: "Virgin Aperol Spritz",
      category: "mocktails",
      description: "A sparkling blend of Aperol and soda water, without the prosecco.",
      rating: "3.7",
      reviews: "300",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Aperol", amount: "2", unit: "parts" },
        { name: "Soda Water", amount: "4", unit: "parts" },
        { name: "Orange Slice", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add Aperol and soda water to glass with ice",
        "Stir gently",
        "Garnish with orange slice",
      ],
      tips: "Use plenty of ice for a refreshing spritz.",
    },
    {
      name: "Virgin French 75",
      category: "mocktails",
      description: "A bubbly blend of lemon, sugar, and sparkling water, without the gin and champagne.",
      rating: "3.6",
      reviews: "200",
      difficulty: "Easy",
      prepTime: "4 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lemon Juice", amount: "0.5", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
        { name: "Sparkling Water", amount: "3", unit: "parts" },
      ],
      steps: [
        "Mix lemon juice and simple syrup",
        "Top with sparkling water",
        "Garnish with lemon twist",
      ],
      tips: "Serve in a flute for elegance.",
    },
    {
      name: "Virgin Caipirinha",
      category: "mocktails",
      description: "A Brazilian blend of lime and sugar, without the cachaça.",
      rating: "3.5",
      reviews: "100",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Fresh Lime", amount: "1", unit: "whole, cut into wedges" },
        { name: "Sugar", amount: "2", unit: "tsp" },
        { name: "Soda Water", amount: "1", unit: "part" },
      ],
      steps: [
        "Muddle lime and sugar in glass",
        "Add soda water and ice",
        "Stir well",
      ],
      tips: "Use plenty of ice for a refreshing drink.",
    },
    {
      name: "Virgin Moscow Mule",
      category: "mocktails",
      description: "A spicy blend of ginger beer and lime, without the vodka.",
      rating: "3.4",
      reviews: "50",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Ginger Beer", amount: "4", unit: "parts" },
        { name: "Fresh Lime Juice", amount: "0.5", unit: "part" },
        { name: "Lime Wedge", amount: "1", unit: "piece" },
      ],
      steps: [
        "Add ginger beer and lime juice to mug with ice",
        "Stir gently",
        "Garnish with lime wedge",
      ],
      tips: "Serve in a copper mug for tradition and chill.",
    },
    {
      name: "Virgin Sidecar",
      category: "mocktails",
      description: "A citrusy blend of orange and lemon, without the cognac.",
      rating: "3.3",
      reviews: "30",
      difficulty: "Easy",
      prepTime: "3 mins",
      serves: "1 serving",
      ingredients: [
        { name: "Orange Juice", amount: "2", unit: "parts" },
        { name: "Fresh Lemon Juice", amount: "1", unit: "part" },
        { name: "Simple Syrup", amount: "0.5", unit: "part" },
      ],
      steps: [
        "Mix orange juice, lemon juice, and simple syrup",
        "Pour over ice",
        "Garnish with orange twist",
      ],
      tips: "Chill the glass for best results.",
    },
  ],
  craftbeer: [
    {
      name: "Hazy IPA",
      category: "craftbeer",
      description: "A juicy, hazy India Pale Ale with tropical fruit notes and a soft mouthfeel.",
      rating: "4.8",
      reviews: "2.3k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "10", unit: "lbs" },
        { name: "Flaked Oats", amount: "2", unit: "lbs" },
        { name: "Wheat Malt", amount: "1.5", unit: "lbs" },
        { name: "Citra Hops", amount: "3", unit: "oz" },
        { name: "Mosaic Hops", amount: "3", unit: "oz" },
        { name: "Yeast (London Ale III)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash grains at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, adding hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Dry hop with Citra and Mosaic after primary fermentation.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Dry hop at lower temperatures for maximum aroma. Enjoy fresh!",
    },
    {
      name: "American Pale Ale",
      category: "craftbeer",
      description: "A balanced pale ale with citrusy hops and a crisp finish.",
      rating: "4.7",
      reviews: "1.9k",
      difficulty: "Easy",
      prepTime: "12 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "9", unit: "lbs" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Cascade Hops", amount: "2.5", unit: "oz" },
        { name: "Centennial Hops", amount: "1.5", unit: "oz" },
        { name: "Yeast (American Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash grains at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, adding hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Use fresh hops for a brighter aroma.",
    },
    {
      name: "Belgian Witbier",
      category: "craftbeer",
      description: "A refreshing wheat beer with orange peel and coriander.",
      rating: "4.6",
      reviews: "1.7k",
      difficulty: "Easy",
      prepTime: "10 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "5", unit: "lbs" },
        { name: "Wheat Malt", amount: "5", unit: "lbs" },
        { name: "Flaked Oats", amount: "1", unit: "lb" },
        { name: "Bitter Orange Peel", amount: "1", unit: "oz" },
        { name: "Coriander Seed", amount: "0.5", unit: "oz" },
        { name: "Saaz Hops", amount: "1.5", unit: "oz" },
        { name: "Yeast (Belgian Wit)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash grains at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, adding spices and hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-22°C (64-72°F) for 7 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Add orange peel and coriander in the last 10 minutes of the boil.",
    },
    {
      name: "German Pilsner",
      category: "craftbeer",
      description: "A crisp, clean lager with floral hop aroma and a dry finish.",
      rating: "4.7",
      reviews: "1.5k",
      difficulty: "Medium",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "9", unit: "lbs" },
        { name: "Saaz Hops", amount: "3", unit: "oz" },
        { name: "Yeast (German Lager)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 10°C (50°F) for 2 weeks, then lager at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Use soft water for authentic pilsner character.",
    },
    {
      name: "Robust Porter",
      category: "craftbeer",
      description: "A dark ale with roasted malt, chocolate, and caramel notes.",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "8", unit: "lbs" },
        { name: "Chocolate Malt", amount: "1", unit: "lb" },
        { name: "Crystal Malt", amount: "0.5", unit: "lb" },
        { name: "Black Patent Malt", amount: "0.25", unit: "lb" },
        { name: "East Kent Goldings Hops", amount: "2", unit: "oz" },
        { name: "Yeast (English Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Let it age for a smoother, richer flavor.",
    },
    {
      name: "Milk Stout",
      category: "craftbeer",
      description: "A creamy, sweet stout with notes of coffee and chocolate.",
      rating: "4.8",
      reviews: "1.8k",
      difficulty: "Medium",
      prepTime: "16 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "7", unit: "lbs" },
        { name: "Roasted Barley", amount: "1", unit: "lb" },
        { name: "Lactose", amount: "1", unit: "lb" },
        { name: "Chocolate Malt", amount: "0.5", unit: "lb" },
        { name: "Fuggle Hops", amount: "2", unit: "oz" },
        { name: "Yeast (English Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops and lactose as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 12 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Lactose adds sweetness and body—do not substitute.",
    },
    {
      name: "West Coast IPA",
      category: "craftbeer",
      description: "A hop-forward IPA with pine, citrus, and a dry, bitter finish.",
      rating: "4.7",
      reviews: "2.0k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "10", unit: "lbs" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Simcoe Hops", amount: "2", unit: "oz" },
        { name: "Centennial Hops", amount: "2", unit: "oz" },
        { name: "Cascade Hops", amount: "2", unit: "oz" },
        { name: "Yeast (California Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Dry hop with Simcoe and Centennial after primary fermentation.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Use a clean yeast for a crisp finish.",
    },
    {
      name: "Vienna Lager",
      category: "craftbeer",
      description: "A smooth amber lager with toasty malt and gentle bitterness.",
      rating: "4.5",
      reviews: "1.1k",
      difficulty: "Medium",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Vienna Malt", amount: "7", unit: "lbs" },
        { name: "Munich Malt", amount: "2", unit: "lbs" },
        { name: "Pilsner Malt", amount: "1", unit: "lb" },
        { name: "Hallertau Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Lager)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 10°C (50°F) for 2 weeks, then lager at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Lagering brings out the smooth malt character.",
    },
    {
      name: "English Bitter",
      category: "craftbeer",
      description: "A sessionable ale with caramel malt and earthy hops.",
      rating: "4.4",
      reviews: "900",
      difficulty: "Easy",
      prepTime: "10 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "7", unit: "lbs" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Fuggle Hops", amount: "2", unit: "oz" },
        { name: "Yeast (English Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 7 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Serve at cellar temperature for best flavor.",
    },
    {
      name: "Irish Red Ale",
      category: "craftbeer",
      description: "A malty red ale with subtle caramel and roasted notes.",
      rating: "4.5",
      reviews: "1.3k",
      difficulty: "Easy",
      prepTime: "12 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "8", unit: "lbs" },
        { name: "Crystal Malt", amount: "1.5", unit: "lbs" },
        { name: "Roasted Barley", amount: "0.25", unit: "lb" },
        { name: "East Kent Goldings Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Irish Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "A touch of roasted barley gives the signature color.",
    },
    {
      name: "Czech Pilsner",
      category: "craftbeer",
      description: "A golden lager with spicy Saaz hops and a crisp, refreshing finish.",
      rating: "4.7",
      reviews: "1.4k",
      difficulty: "Medium",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "8", unit: "lbs" },
        { name: "Saaz Hops", amount: "3.5", unit: "oz" },
        { name: "Yeast (Czech Lager)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 10°C (50°F) for 2 weeks, then lager at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Use soft water for a classic Czech profile.",
    },
    {
      name: "Oatmeal Stout",
      category: "craftbeer",
      description: "A smooth, full-bodied stout with roasted coffee and chocolate notes.",
      rating: "4.8",
      reviews: "1.6k",
      difficulty: "Medium",
      prepTime: "16 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "7", unit: "lbs" },
        { name: "Flaked Oats", amount: "1.5", unit: "lbs" },
        { name: "Roasted Barley", amount: "1", unit: "lb" },
        { name: "Chocolate Malt", amount: "0.5", unit: "lb" },
        { name: "Fuggle Hops", amount: "2", unit: "oz" },
        { name: "Yeast (English Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 12 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Oats add creaminess and a silky mouthfeel.",
    },
    {
      name: "Double IPA",
      category: "craftbeer",
      description: "A bold, hop-saturated ale with high bitterness and strong citrus aroma.",
      rating: "4.9",
      reviews: "2.5k",
      difficulty: "Hard",
      prepTime: "16 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "12", unit: "lbs" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Simcoe Hops", amount: "3", unit: "oz" },
        { name: "Citra Hops", amount: "3", unit: "oz" },
        { name: "Yeast (California Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Dry hop with Simcoe and Citra after primary fermentation.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Use plenty of late addition hops for maximum aroma.",
    },
    {
      name: "Saison",
      category: "craftbeer",
      description: "A farmhouse ale with peppery yeast, citrus, and a dry finish.",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "8", unit: "lbs" },
        { name: "Wheat Malt", amount: "2", unit: "lbs" },
        { name: "Saaz Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Saison)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment warm (22-28°C/72-82°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Let fermentation temperature rise for more yeast character.",
    },
    {
      name: "Barleywine",
      category: "craftbeer",
      description: "A strong, malty ale with rich caramel and dried fruit notes.",
      rating: "4.8",
      reviews: "1.9k",
      difficulty: "Hard",
      prepTime: "30 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "15", unit: "lbs" },
        { name: "Crystal Malt", amount: "2", unit: "lbs" },
        { name: "East Kent Goldings Hops", amount: "3", unit: "oz" },
        { name: "Yeast (English Ale)", amount: "2", unit: "packs" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 90 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 14 days.",
        "Bottle or keg and age for at least 2 weeks.",
      ],
      tips: "Aging improves complexity and smoothness.",
    },
    {
      name: "Belgian Dubbel",
      category: "craftbeer",
      description: "A rich, malty Trappist ale with dark fruit and caramel flavors.",
      rating: "4.7",
      reviews: "1.6k",
      difficulty: "Medium",
      prepTime: "18 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "8", unit: "lbs" },
        { name: "Munich Malt", amount: "2", unit: "lbs" },
        { name: "Special B Malt", amount: "0.5", unit: "lb" },
        { name: "Candi Sugar", amount: "1", unit: "lb" },
        { name: "Saaz Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Belgian Abbey)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops and candi sugar as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 20°C (68°F) for 12 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Candi sugar boosts ABV and adds complexity.",
    },
    {
      name: "American Brown Ale",
      category: "craftbeer",
      description: "A nutty, malty ale with chocolate and caramel undertones.",
      rating: "4.5",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "12 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "8", unit: "lbs" },
        { name: "Chocolate Malt", amount: "1", unit: "lb" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Willamette Hops", amount: "2", unit: "oz" },
        { name: "Yeast (American Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Try a touch of honey malt for extra depth.",
    },
    {
      name: "Rye IPA",
      category: "craftbeer",
      description: "A spicy, hoppy IPA with rye malt and citrus-forward hops.",
      rating: "4.6",
      reviews: "1.3k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "9", unit: "lbs" },
        { name: "Rye Malt", amount: "2", unit: "lbs" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Amarillo Hops", amount: "2", unit: "oz" },
        { name: "Simcoe Hops", amount: "2", unit: "oz" },
        { name: "Yeast (American Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Dry hop with Amarillo and Simcoe after primary fermentation.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Rye adds a spicy complexity to the finish.",
    },
    {
      name: "Schwarzbier",
      category: "craftbeer",
      description: "A dark German lager with smooth roast and subtle bitterness.",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Medium",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "7", unit: "lbs" },
        { name: "Munich Malt", amount: "2", unit: "lbs" },
        { name: "Carafa Special II", amount: "0.5", unit: "lb" },
        { name: "Hallertau Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Lager)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 10°C (50°F) for 2 weeks, then lager at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Cold conditioning smooths out the roast character.",
    },
    {
      name: "American Wheat Ale",
      category: "craftbeer",
      description: "A light, refreshing ale with wheat malt and a hint of citrus.",
      rating: "4.4",
      reviews: "900",
      difficulty: "Easy",
      prepTime: "10 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "5", unit: "lbs" },
        { name: "Wheat Malt", amount: "5", unit: "lbs" },
        { name: "Cascade Hops", amount: "2", unit: "oz" },
        { name: "Yeast (American Wheat)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 7 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Add a slice of orange for garnish.",
    },
    {
      name: "Belgian Tripel",
      category: "craftbeer",
      description: "A strong, golden ale with fruity esters and a dry, spicy finish.",
      rating: "4.9",
      reviews: "2.1k",
      difficulty: "Hard",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "10", unit: "lbs" },
        { name: "Candi Sugar", amount: "2", unit: "lbs" },
        { name: "Saaz Hops", amount: "2.5", unit: "oz" },
        { name: "Yeast (Belgian Abbey)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 90 minutes, add hops and candi sugar as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 20°C (68°F) for 14 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Candi sugar boosts ABV and keeps the finish dry.",
    },
    {
      name: "Baltic Porter",
      category: "craftbeer",
      description: "A strong, smooth porter with dark fruit and toffee notes.",
      rating: "4.7",
      reviews: "1.5k",
      difficulty: "Hard",
      prepTime: "21 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "8", unit: "lbs" },
        { name: "Munich Malt", amount: "2", unit: "lbs" },
        { name: "Chocolate Malt", amount: "1", unit: "lb" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Hallertau Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Lager)", amount: "2", unit: "packs" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 12°C (54°F) for 14 days, then lager at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Cold fermentation yields a clean, smooth finish.",
    },
    {
      name: "Scotch Ale",
      category: "craftbeer",
      description: "A rich, malty ale with caramel, toffee, and a warming finish.",
      rating: "4.7",
      reviews: "1.2k",
      difficulty: "Medium",
      prepTime: "18 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "10", unit: "lbs" },
        { name: "Crystal Malt", amount: "2", unit: "lbs" },
        { name: "Peated Malt", amount: "0.25", unit: "lb" },
        { name: "East Kent Goldings Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Scottish Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 16-18°C (60-64°F) for 12 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "A touch of peated malt adds authentic Scottish character.",
    },
    {
      name: "American Porter",
      category: "craftbeer",
      description: "A robust, dark ale with chocolate, coffee, and caramel notes.",
      rating: "4.6",
      reviews: "1.1k",
      difficulty: "Medium",
      prepTime: "14 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "8", unit: "lbs" },
        { name: "Chocolate Malt", amount: "1", unit: "lb" },
        { name: "Crystal Malt", amount: "1", unit: "lb" },
        { name: "Black Patent Malt", amount: "0.5", unit: "lb" },
        { name: "Willamette Hops", amount: "2", unit: "oz" },
        { name: "Yeast (American Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Try cold steeping some of the dark malts for a smoother finish.",
    },
    {
      name: "Kölsch",
      category: "craftbeer",
      description: "A light, crisp German ale with subtle fruitiness and a clean finish.",
      rating: "4.5",
      reviews: "1.0k",
      difficulty: "Medium",
      prepTime: "18 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "8", unit: "lbs" },
        { name: "Wheat Malt", amount: "1", unit: "lb" },
        { name: "Hallertau Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Kölsch)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 65°C (149°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 15°C (59°F) for 10 days, then cold condition at 2°C (35°F) for 1 week.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Cold conditioning gives Kölsch its signature clarity.",
    },
    {
      name: "Belgian Blonde Ale",
      category: "craftbeer",
      description: "A golden ale with fruity esters, light spice, and a dry finish.",
      rating: "4.7",
      reviews: "1.3k",
      difficulty: "Medium",
      prepTime: "16 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pilsner Malt", amount: "9", unit: "lbs" },
        { name: "Munich Malt", amount: "1", unit: "lb" },
        { name: "Candi Sugar", amount: "1", unit: "lb" },
        { name: "Saaz Hops", amount: "2", unit: "oz" },
        { name: "Yeast (Belgian Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 66°C (151°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops and candi sugar as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 20°C (68°F) for 12 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Candi sugar keeps the finish dry and light.",
    },
    {
      name: "American Amber Ale",
      category: "craftbeer",
      description: "A balanced amber ale with caramel malt and moderate hop bitterness.",
      rating: "4.6",
      reviews: "1.2k",
      difficulty: "Easy",
      prepTime: "12 days",
      serves: "5 gallons",
      ingredients: [
        { name: "Pale Malt", amount: "8", unit: "lbs" },
        { name: "Crystal Malt", amount: "1.5", unit: "lbs" },
        { name: "Munich Malt", amount: "0.5", unit: "lb" },
        { name: "Cascade Hops", amount: "2", unit: "oz" },
        { name: "Yeast (American Ale)", amount: "1", unit: "pack" },
      ],
      steps: [
        "Mash at 67°C (153°F) for 60 minutes.",
        "Boil wort for 60 minutes, add hops as scheduled.",
        "Cool wort and pitch yeast.",
        "Ferment at 18-20°C (64-68°F) for 10 days.",
        "Bottle or keg and carbonate.",
      ],
      tips: "Balance caramel malt and hops for a classic amber profile.",
    },
  ],
}
